AB#58 Adds authorization UI components
PSU-DevBoards/devboards-front-end pull request #7
Opened 2021-09-29 19:09 UTC by kpjVideo

Separates Header into a component.
Adds component for login, logout, and register buttons.
Adds loading page for use during auth0 grant init.

2021-09-29 19:11 UTC, kpjVideo commented
Whoops, I appear to have merge conflicts here, let me try to resolve that first.

2021-10-02 02:15 UTC, joenoon16510 approved these changes

2021-10-03 14:57 UTC, zlix12 requested changes

2021-10-03 14:57 UTC, zlix12 commented on src/App.tsx
> +import Auth from './pages/Auth';
This import causes the application to fail as `./pages/Auth` does not exist in this branch.

2021-10-03 14:57 UTC, zlix12 commented on src/App.tsx
>  import { BrowserRouter as Router, Route } from 'react-router-dom';
`react-router-dom` is also not listed in the project dependencies.

2021-10-03 18:43 UTC, joenoon16510 approved these changes

2021-10-03 18:53 UTC, zlix12 approved these changes
LGTM

2021-10-03 18:53 UTC, merged